Add scripts for Landsacpe IOT / Ubuntu Core. Update readme.md to match
canonical/landscape-scripts pull request #10
Opened 2024-03-05 09:47 UTC by mcw-work

2024-03-05 19:34 UTC, Perfect5th requested changes

2024-03-05 19:34 UTC, Perfect5th commented on README.md
> +    - [**install-snap.py**](./core/snaps/install-snap.py)
Please mention in the README that the `install-` scripts require `python3-requests` deb (or PyPI `requests`). It's installed automatically in a lot of environments, but that might not be the case in all environments.

2024-03-06 13:32 UTC, mcw-work commented on README.md
> +    - [**install-snap.py**](./core/snaps/install-snap.py)
True - although technically this section is for Core based clients so has to be the snap and we know that all dependencies for these are in the snap. I'll add it anyway..

2024-03-06 18:42 UTC, Perfect5th approved these changes
LGTM, thanks!

2024-03-06 18:42 UTC, merged